// Mocks generated by Mockito 5.4.6 from annotations
// in test_task/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:connectivity_plus/connectivity_plus.dart' as _i4;
import 'package:dio/dio.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:talker/talker.dart' as _i2;
import 'package:test_task/features/auth/data/data_sources/user_local_data_source.dart'
    as _i11;
import 'package:test_task/features/auth/data/data_sources/user_remote_data_source.dart'
    as _i7;
import 'package:test_task/features/auth/data/models/user_model/user_model.dart'
    as _i9;
import 'package:test_task/features/core/core.dart' as _i3;
import 'package:test_task/features/core/database/dao/comments_dao.dart' as _i6;
import 'package:test_task/features/core/database/dao/posts_dao.dart' as _i5;
import 'package:test_task/features/core/services/connectivity_service.dart'
    as _i12;
import 'package:test_task/features/posts/data/data_sources/posts_local_data_source.dart'
    as _i16;
import 'package:test_task/features/posts/data/data_sources/posts_remote_data_source.dart'
    as _i13;
import 'package:test_task/features/posts/data/models/comment_model/comment_model.dart'
    as _i15;
import 'package:test_task/features/posts/data/models/post_model/post_model.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTalker_0 extends _i1.SmartFake implements _i2.Talker {
  _FakeTalker_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiClientI_1 extends _i1.SmartFake implements _i3.ApiClientI {
  _FakeApiClientI_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectivity_2 extends _i1.SmartFake implements _i4.Connectivity {
  _FakeConnectivity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostsDao_3 extends _i1.SmartFake implements _i5.PostsDao {
  _FakePostsDao_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentsDao_4 extends _i1.SmartFake implements _i6.CommentsDao {
  _FakeCommentsDao_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i7.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Talker get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeTalker_0(this, Invocation.getter(#logger)),
          )
          as _i2.Talker);

  @override
  _i3.ApiClientI get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClientI_1(this, Invocation.getter(#apiClient)),
          )
          as _i3.ApiClientI);

  @override
  _i8.Future<_i9.UserModel?> getUserByEmail({
    required String? email,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [], {
              #email: email,
              #cancelToken: cancelToken,
            }),
            returnValue: _i8.Future<_i9.UserModel?>.value(),
          )
          as _i8.Future<_i9.UserModel?>);
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i11.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> saveUserId(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserId, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int?> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i8.Future<int?>.value(),
          )
          as _i8.Future<int?>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i12.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Connectivity get connectivity =>
      (super.noSuchMethod(
            Invocation.getter(#connectivity),
            returnValue: _FakeConnectivity_2(
              this,
              Invocation.getter(#connectivity),
            ),
          )
          as _i4.Connectivity);

  @override
  _i8.Future<bool> get isOnline =>
      (super.noSuchMethod(
            Invocation.getter(#isOnline),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i8.Stream<bool>.empty(),
          )
          as _i8.Stream<bool>);
}

/// A class which mocks [PostsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsRemoteDataSource extends _i1.Mock
    implements _i13.PostsRemoteDataSource {
  MockPostsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiClientI get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClientI_1(this, Invocation.getter(#apiClient)),
          )
          as _i3.ApiClientI);

  @override
  _i8.Future<List<_i14.PostModel>> getPosts({
    required int? page,
    int? limit = 10,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {
              #page: page,
              #limit: limit,
              #cancelToken: cancelToken,
            }),
            returnValue: _i8.Future<List<_i14.PostModel>>.value(
              <_i14.PostModel>[],
            ),
          )
          as _i8.Future<List<_i14.PostModel>>);

  @override
  _i8.Future<List<_i15.CommentModel>> getComments({
    required int? postId,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [], {
              #postId: postId,
              #cancelToken: cancelToken,
            }),
            returnValue: _i8.Future<List<_i15.CommentModel>>.value(
              <_i15.CommentModel>[],
            ),
          )
          as _i8.Future<List<_i15.CommentModel>>);
}

/// A class which mocks [PostsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsLocalDataSource extends _i1.Mock
    implements _i16.PostsLocalDataSource {
  MockPostsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.PostsDao get postsDao =>
      (super.noSuchMethod(
            Invocation.getter(#postsDao),
            returnValue: _FakePostsDao_3(this, Invocation.getter(#postsDao)),
          )
          as _i5.PostsDao);

  @override
  _i6.CommentsDao get commentsDao =>
      (super.noSuchMethod(
            Invocation.getter(#commentsDao),
            returnValue: _FakeCommentsDao_4(
              this,
              Invocation.getter(#commentsDao),
            ),
          )
          as _i6.CommentsDao);

  @override
  _i8.Future<List<_i14.PostModel>> getPosts({
    required int? page,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {#page: page, #limit: limit}),
            returnValue: _i8.Future<List<_i14.PostModel>>.value(
              <_i14.PostModel>[],
            ),
          )
          as _i8.Future<List<_i14.PostModel>>);

  @override
  _i8.Future<void> savePosts(List<_i14.PostModel>? posts, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#savePosts, [posts, page]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i15.CommentModel>> getCommentsByPostId({
    required int? postId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentsByPostId, [], {#postId: postId}),
            returnValue: _i8.Future<List<_i15.CommentModel>>.value(
              <_i15.CommentModel>[],
            ),
          )
          as _i8.Future<List<_i15.CommentModel>>);

  @override
  _i8.Future<void> saveComments(List<_i15.CommentModel>? comments) =>
      (super.noSuchMethod(
            Invocation.method(#saveComments, [comments]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
